export const companyTexts = {
  pageTitle: 'Empresas',
  pageSubtitle: 'Gestión del catálogo de empresas. Crea y edita empresas directamente desde esta pantalla.',
  newCompanyAction: 'Nueva empresa',

  listTitle: 'Listado de empresas',
  listSubtitle: 'Explora el catálogo y abre la ficha de la empresa seleccionada.',
  listSearchPlaceholder: 'Buscar por código, nombre o razón social',
  listLoadingMessage: 'Cargando empresas...',
  listLoadFailedMessage: 'No se pudo cargar el listado de empresas. Reintenta.',
  listEmptyMessage: 'No hay empresas registradas. Crea la primera empresa.',
  listEmptySearchMessage: 'No hay empresas que coincidan con la búsqueda actual.',

  listMetaTaxIdLabel: 'CIF/NIF',
  listMetaCountryLabel: 'País',
  listMetaStartDateLabel: 'Inicio',
  emptyValueLabel: 'Sin dato',

  columnCodeLabel: 'Código',
  columnNameLabel: 'Nombre',
  columnLegalNameLabel: 'Razón social',
  columnTaxIdLabel: 'CIF/NIF',
  columnCountryLabel: 'País',
  columnActiveLabel: 'Activa',
  columnActionsLabel: 'Acciones',
  editAction: 'Editar',

  formCreateTitle: 'Nueva empresa',
  formEditTitle: 'Editar empresa',
  formViewTitle: 'Detalle de empresa',
  formSaveAction: 'Guardar',
  formCancelAction: 'Cancelar',
  formEditAction: 'Editar',
  draftLabel: 'Borrador',

  detailPanelTitle: 'Ficha de empresa',
  detailHeaderRuleSystemLabel: 'Sistema de reglas',
  detailHeaderCompanyCodeLabel: 'Código empresa',
  detailHeaderStartDateLabel: 'Fecha inicio',
  detailViewEmptyValue: '—',
  detailSectionIdentitySubtitle: 'Datos base de identificación y vigencia de la empresa.',
  detailSectionFiscalSubtitle: 'Razón social y datos fiscales que enriquecen el agregado.',
  detailSectionAddressSubtitle: 'Información de localización usada en la ficha de empresa.',
  detailDescriptionEmpty: 'Sin descripción informada',
  detailAddressEmpty: 'No hay dirección informada para esta empresa.',

  sectionIdentityTitle: 'Identificación',
  fieldRuleSystemCodeLabel: 'Sistema de reglas',
  fieldCompanyCodeLabel: 'Código empresa',
  fieldNameLabel: 'Nombre',
  fieldDescriptionLabel: 'Descripción',
  fieldStartDateLabel: 'Fecha inicio',

  sectionFiscalTitle: 'Datos fiscales',
  fieldLegalNameLabel: 'Razón social',
  fieldTaxIdLabel: 'CIF/NIF',

  sectionAddressTitle: 'Dirección',
  fieldStreetLabel: 'Dirección',
  fieldCityLabel: 'Ciudad',
  fieldPostalCodeLabel: 'Código postal',
  fieldRegionCodeLabel: 'Provincia',
  fieldCountryCodeLabel: 'País (ISO 3166-1 alpha-3)',

  detailLoadingMessage: 'Cargando detalle...',
  detailLoadFailedMessage: 'No se pudo cargar el detalle de la empresa.',
  detailNotFoundMessage: 'No se encontró la empresa seleccionada.',

  submitSuccessCreated: 'Empresa creada correctamente.',
  submitSuccessUpdated: 'Empresa actualizada correctamente.',

  emptyDetailTitle: 'Selecciona o crea una empresa',
  emptyDetailDescription: 'Selecciona una empresa de la lista para editarla, o pulsa "Nueva empresa" para crear una.',

  activeLabel: 'Activa',
  inactiveLabel: 'Inactiva',
};
