export const EMPLOYEE_UI_TOKENS = {
  spacing: {
    xs: '0.25rem',
    s: '0.5rem',
    m: '0.75rem',
    l: '1rem',
    xl: '1.25rem',
  },
  radius: {
    s: '0.5rem',
    m: '0.75rem',
    pill: '999px',
  },
  colors: {
    background: '#f7f9fc',
    surface: '#ffffff',
    surfaceMuted: '#f4f7fb',
    border: '#d8e0ea',
    borderStrong: '#c2ccd8',
    text: '#1f3246',
    textMuted: '#5c7085',
    primary: '#2c4f72',
    primaryMuted: '#e8f1fb',
    danger: '#8d2b2b',
    dangerMuted: '#fff3f3',
    success: '#1f5a3b',
    successMuted: '#f2fbf5',
    warning: '#735012',
    warningMuted: '#fff9eb',
  },
} as const;