export const catalogTexts = {
  pageTitle: 'Catalogos',
  pageSubtitle: 'Selecciona un rule system y un tipo para consultar y crear entidades de catalogo.',
  selectorLabel: 'Rule system',
  selectorPlaceholder: 'Selecciona un rule system',
  typePanelTitle: 'Rule entity types',
  entityPanelTitle: 'Rule entities',
  entityPanelSubtitle: 'Listado filtrado por rule system y tipo seleccionado.',
  createPanelTitle: 'Nuevo rule entity',
  createPanelSubtitle: 'Alta en el contexto seleccionado de rule system y type.',
  emptyNoRuleSystem: 'Selecciona un rule system para continuar.',
  emptyNoType: 'Selecciona un rule entity type para ver entidades.',
  emptyNoEntities: 'No entities yet for this context.',
  loadingRuleSystems: 'Cargando rule systems...',
  loadingRuleEntityTypes: 'Cargando rule entity types...',
  loadingRuleEntities: 'Cargando rule entities...',
  listCodeHeader: 'Code',
  listNameHeader: 'Name',
  listActiveHeader: 'Active',
  listStartDateHeader: 'Start date',
  listEndDateHeader: 'End date',
  activeYes: 'Yes',
  activeNo: 'No',
  createCodeLabel: 'Code',
  createNameLabel: 'Name',
  createDescriptionLabel: 'Description',
  createStartDateLabel: 'Start date',
  createEndDateLabel: 'End date',
  createSubmitAction: 'Crear rule entity',
  createCodeRequired: 'Code is required.',
  createCodeMaxLength: 'Code must have at most 30 characters.',
  createNameRequired: 'Name is required.',
  createNameMaxLength: 'Name must have at most 100 characters.',
  createDescriptionMaxLength: 'Description must have at most 500 characters.',
  createStartDateRequired: 'Start date is required.',
  createEndDateInvalidRange: 'End date must be greater than or equal to start date.',
  createSuccessMessage: 'Rule entity creada correctamente.',
  genericErrorMessage: 'No se pudo completar la operacion. Reintenta.',
  creatingMessage: 'Creando rule entity...',
} as const;
