import { EmployeeListItemModel } from '../models/employee-list-item.model';

export const employeeDirectorySeed: ReadonlyArray<EmployeeListItemModel> = [
  {
    ruleSystemCode: 'PA-ES',
    employeeTypeCode: 'STAFF',
    employeeNumber: '00012345',
    displayName: 'Lidia Morales',
    workCenter: 'Madrid HQ',
    statusLabel: 'Active',
  },
  {
    ruleSystemCode: 'PA-ES',
    employeeTypeCode: 'MANAGER',
    employeeNumber: '00012780',
    displayName: 'Javier Paredes',
    workCenter: 'Madrid HQ',
    statusLabel: 'Active',
  },
  {
    ruleSystemCode: 'PA-ES',
    employeeTypeCode: 'STAFF',
    employeeNumber: '00020311',
    displayName: 'Marta Serrano',
    workCenter: 'Barcelona North',
    statusLabel: 'Active',
  },
  {
    ruleSystemCode: 'PA-ES',
    employeeTypeCode: 'STAFF',
    employeeNumber: '00031809',
    displayName: 'Nuria Cid',
    workCenter: 'Valencia South',
    statusLabel: 'On leave',
  },
  {
    ruleSystemCode: 'PA-ES',
    employeeTypeCode: 'STAFF',
    employeeNumber: '00041274',
    displayName: 'Diego Colomer',
    workCenter: 'Bilbao Center',
    statusLabel: 'Active',
  },
  {
    ruleSystemCode: 'PA-ES',
    employeeTypeCode: 'CONTRACTOR',
    employeeNumber: '00012345',
    displayName: 'Lidia Morales Contractor',
    workCenter: 'Madrid HQ',
    statusLabel: 'Active',
  },
  {
    ruleSystemCode: 'PA-ES',
    employeeTypeCode: 'TEMP',
    employeeNumber: '00057822',
    displayName: 'Aitana Llorens',
    workCenter: 'Sevilla East',
    statusLabel: 'Suspended',
  },
];
