export const employeeTexts = {
  masterTitle: 'Employees',
  masterSubtitle: 'Search by business key and select an employee to open vertical sections.',
  searchLabel: 'Search employee',
  searchPlaceholder: 'Rule system, type, number, name or work center',
  openAction: 'Open first result',
  resultEmployeesTitle: 'Matching employees',
  noResultEmployeesTitle: 'No matching employees',
  noResultEmployeesDescription: 'Adjust search criteria to find employees by business key.',
  detailPanelTitle: 'Employee detail',
  detailPanelSubtitle: 'Business view of the employee profile, aligned with current vertical routes.',
  emptyDetailTitle: 'Select an employee to start',
  emptyDetailDescription:
    'Use the employee list to open a detail area. No technical IDs are used in this flow.',
  detailIdentityTitle: 'Employee identity',
  detailAvatarPlaceholderAriaLabel: 'Employee avatar placeholder',
  detailHeaderRuleSystemLabel: 'Rule system',
  detailHeaderEmployeeTypeLabel: 'Employee type',
  detailHeaderEmployeeNumberLabel: 'Employee number',
  detailHeaderWorkCenterLabel: 'Work center',
  detailHeaderStatusLabel: 'Status',
  detailHeaderAvatarFallback: 'NA',
  unknownEmployeeName: 'External employee context',
  unknownEmployeeWorkCenter: 'Unknown work center',
  unknownEmployeeStatus: 'Unknown status',
  detailLoadingMessage: 'Cargando detalle del empleado...',
  detailNotFoundMessage: 'No se encontro detalle para la clave de negocio seleccionada.',
  detailLoadFailedMessage: 'No se pudo cargar el detalle del empleado. Reintenta navegando de nuevo.',
  overviewNavLabel: 'Overview',
  contactNavLabel: 'Contact',
  presenceNavLabel: 'Presence',
  detailAreasNavLabel: 'Employee business areas',
  summaryAreaLabel: 'Resumen',
  personalAreaLabel: 'Personales',
  laborAreaLabel: 'Laborales',
  organizationalAreaLabel: 'Organizativos',
  payrollAreaLabel: 'Nomina',
  areaDisabledLabel: 'Disponible en siguiente iteracion',
  navRoutingHint:
    'Resumen, Personales y Laborales ya navegan sobre los verticales activos. Organizativos y Nomina quedan preparados.',
  timelineTitle: 'Journey',
  timelineEventsSingularLabel: 'evento',
  timelineEventsPluralLabel: 'eventos',
  timelineLastEventLabel: 'Ultimo',
  timelineExpandActionLabel: 'Expandir journey',
  timelineCollapseActionLabel: 'Contraer journey',
  timelineStatusCompletedLabel: 'Completado',
  timelineStatusCurrentLabel: 'Actual',
  timelineStatusFutureLabel: 'Futuro',
  timelineNoEventsMessage: 'No hay eventos disponibles.',
  timelineLoadingMessage: 'Cargando journey del empleado...',
  timelineLoadFailedMessage: 'No se pudo cargar el journey del empleado.',
  sectionShellCreateAction: 'Crear',
  sectionShellEditAction: 'Editar',
  sectionShellCancelAction: 'Cancelar',
  sectionShellBusyMessage: 'Procesando cambios...',
  sectionDemoTitle: 'Seccion editable (demo)',
  sectionDemoSubtitle: 'Patron base para separar estado local de UI y datos remotos.',
  sectionDemoViewMessage: 'Estado de lectura. Usa Crear o Editar para abrir modo de trabajo local.',
  sectionDemoCreatingMessage: 'Modo creating. Simula la captura de un nuevo registro sin backend real.',
  sectionDemoEditingMessage: 'Modo editing. Simula cambios locales antes de confirmar envio.',
  sectionDemoConfirmingMessage: 'Modo confirming. Punto intermedio antes de ejecutar una accion destructiva.',
  sectionDemoSubmitCreateAction: 'Simular submitCreate()',
  sectionDemoSubmitEditAction: 'Simular submitEdit()',
  sectionDemoConfirmCloseAction: 'Simular confirmClose()',
  sectionDemoCreateSuccessMessage: 'Demo: alta simulada completada.',
  sectionDemoEditSuccessMessage: 'Demo: edicion simulada completada.',
  sectionDemoDeleteSuccessMessage: 'Demo: baja simulada completada.',
  sectionDemoCloseSuccessMessage: 'Demo: cierre simulado completado.',
  slotDemoTitle: 'Contactos por slot (demo)',
  slotDemoSubtitle: 'Patron reusable para alta, edicion y baja por fila con una sola operacion activa.',
  slotAddAction: 'Agregar',
  slotEditAction: 'Editar',
  slotDeleteAction: 'Eliminar',
  slotCancelAction: 'Cancelar',
  slotSaveCreateAction: 'Guardar alta',
  slotSaveEditAction: 'Guardar cambios',
  slotConfirmDeleteMessage: 'Confirma la baja de este registro.',
  slotConfirmDeleteAction: 'Confirmar baja',
  slotEmptyMessage: 'No hay registros cargados.',
  slotKeyFieldLabel: 'Tipo',
  slotValueFieldLabel: 'Valor',
  slotDuplicateKeyErrorMessage: 'No se puede repetir un tipo ya existente.',
  slotCreateSuccessMessage: 'Demo slot: alta simulada completada.',
  slotEditSuccessMessage: 'Demo slot: edicion simulada completada.',
  slotDeleteSuccessMessage: 'Demo slot: baja simulada completada.',
  overviewPanelTitle: 'Employee overview',
  overviewPanelSubtitle: 'Initial summary zone for the employee vertical.',
  contactPanelTitle: 'Employee contact',
  contactPanelSubtitle: 'Base area for contact maintenance and history.',
  presencePanelTitle: 'Employee presence',
  presencePanelSubtitle: 'Base area for presence assignments and timeline.',
  summaryAreaTitle: 'Resumen general',
  summaryAreaSubtitle: 'Contexto administrativo rapido de la ficha.',
  summaryProfileBlockTitle: 'Identidad funcional',
  summaryProfileBlockDescription:
    'Clave de negocio activa y estado de lectura actual para iniciar navegacion segura.',
  summaryLifecycleBlockTitle: 'Hitos laborales',
  summaryLifecycleBlockDescription:
    'Esta zona consolidara altas, cambios y cierres en cuanto exista timeline agregado de backend.',
  summaryPendingBlockTitle: 'Proximos pasos',
  summaryPendingBlockDescription:
    'Preparado para alertas operativas: datos incompletos, revisiones y validaciones pendientes.',
  personalAreaTitle: 'Personales',
  personalAreaSubtitle: 'Bloques de informacion personal y de contacto.',
  personalContactsBlockTitle: 'Contactos',
  personalContactsBlockDescription:
    'Espacio para telefono, email y medios principales de contacto del empleado.',
  contactBlockTitle: 'Contactos',
  contactBlockSubtitle: 'Medios principales de contacto del empleado.',
  contactBlockPrimaryPhoneLabel: 'Telefono principal',
  contactBlockPrimaryEmailLabel: 'Email principal',
  contactBlockSecondaryTitle: 'Otros contactos',
  contactBlockCopyAction: 'Copiar',
  contactBlockEmptyMessage: 'No hay informacion de contacto disponible.',
  contactBlockTypePhone: 'Telefono',
  contactBlockTypeEmail: 'Email',
  contactBlockTypeOther: 'Otro',
  contactsSectionTitle: 'Contactos (edicion)',
  contactsSectionSubtitle: 'Alta, edicion de valor y baja por tipo de contacto.',
  contactsSectionAddAction: 'Agregar contacto',
  contactsSectionEditAction: 'Editar',
  contactsSectionDeleteAction: 'Eliminar',
  contactsSectionCancelAction: 'Cancelar',
  contactsSectionSaveCreateAction: 'Guardar',
  contactsSectionSaveEditAction: 'Guardar',
  contactsSectionConfirmDeleteMessage: 'Confirma la eliminacion de este contacto.',
  contactsSectionConfirmDeleteAction: 'Confirmar eliminacion',
  contactsSectionEmptyMessage: 'No hay contactos cargados.',
  contactsSectionKeyFieldLabel: 'Tipo de contacto',
  contactsSectionValueFieldLabel: 'Valor de contacto',
  contactsSectionRequestFailedMessage: 'No se pudo procesar la operacion de contactos. Reintenta.',
  contactsSectionDuplicateTypeMessage: 'Ya existe un contacto para ese tipo.',
  contactsSectionCreateSuccessMessage: 'Contacto creado correctamente.',
  contactsSectionEditSuccessMessage: 'Contacto actualizado correctamente.',
  contactsSectionDeleteSuccessMessage: 'Contacto eliminado correctamente.',
  personalLoadingMessage: 'Cargando datos personales...',
  contactLoadingMessage: 'Cargando informacion de contacto...',
  contactLoadFailedMessage: 'No se pudo cargar la informacion de contacto.',
  contactBlockPlaceholderNote:
    'Informacion mostrada en modo placeholder hasta disponer de lectura OpenAPI para contactos.',
  personalAddressesBlockTitle: 'Direcciones',
  addressBlockPrimaryLabel: 'Direccion principal',
  addressBlockSecondaryTitle: 'Otras direcciones',
  addressBlockEmptyMessage: 'No hay informacion de direcciones disponible.',
  addressLoadingMessage: 'Cargando informacion de direcciones...',
  addressLoadFailedMessage: 'No se pudo cargar la informacion de direcciones.',
  personalIdentifiersBlockTitle: 'Identificadores',
  identifierBlockPrimaryLabel: 'Identificador principal',
  identifierBlockSecondaryTitle: 'Otros identificadores',
  identifierBlockEmptyMessage: 'No hay identificadores disponibles.',
  identifierLoadFailedMessage: 'No se pudo cargar la informacion de identificadores.',
  identifierBlockIssuingCountryLabel: 'Pais emisor',
  identifierBlockExpirationDateLabel: 'Expira',
  personalAddressesBlockDescription:
    'Bloque preparado para direccion principal, historico y vigencias.',
  laborAreaTitle: 'Laborales',
  laborAreaSubtitle: 'Bloques vinculados a presencia, condicion contractual y clasificacion laboral.',
  laborLoadingMessage: 'Cargando datos laborales...',
  laborPresenceBlockTitle: 'Presence',
  laborPresenceBlockDescription:
    'Area conectada al vertical de presencia con capacidad de historial y estado activo.',
  presenceBlockTitle: 'Presencia',
  presenceBlockCurrentLabel: 'Presencia actual',
  presenceBlockCurrentActiveSectionLabel: 'Presencia activa',
  presenceBlockCurrentSectionLabel: 'Presencia actual',
  presenceBlockCurrentActiveLabel: 'Presencia activa actual.',
  presenceBlockCurrentActiveMostRecentLabel:
    'Hay varias presencias activas; se muestra la mas reciente.',
  presenceBlockCurrentLatestClosedLabel:
    'No hay presencia activa; se muestra la ultima presencia registrada.',
  presenceBlockHistoryTitle: 'Historial de presencias',
  presenceBlockHistoryEmptyMessage: 'Sin periodos anteriores registrados.',
  presenceBlockEmptyMessage: 'No hay presencias disponibles.',
  presenceLoadFailedMessage: 'No se pudo cargar la informacion de presencia.',
  presenceBlockStatusActive: 'Activa',
  presenceBlockStatusClosed: 'Cerrada',
  presenceBlockPeriodLabel: 'Periodo',
  presenceBlockPeriodNumberPrefix: 'periodo',
  presenceBlockOpenPeriodLabel: 'actual',
  presenceBlockCompanyLabel: 'Compania',
  presenceBlockEntryReasonLabel: 'Motivo entrada',
  presenceBlockExitReasonLabel: 'Motivo salida',
  laborContractBlockTitle: 'Contract',
  laborContractBlockDescription:
    'Bloque reservado para tipo contractual, fechas clave y cambios vigentes.',
  contractBlockTitle: 'Contrato',
  contractBlockCurrentLabel: 'Contrato actual',
  contractBlockCurrentActiveSectionLabel: 'Contrato activo',
  contractBlockCurrentSectionLabel: 'Contrato actual',
  contractBlockCurrentActiveLabel: 'Contrato activo actual.',
  contractBlockCurrentActiveMostRecentLabel:
    'Hay varios contratos activos; se muestra el mas reciente.',
  contractBlockCurrentLatestClosedLabel:
    'No hay contrato activo; se muestra el ultimo contrato registrado.',
  contractBlockHistoryTitle: 'Historial de contratos',
  contractBlockHistoryEmptyMessage: 'Sin periodos contractuales anteriores registrados.',
  contractBlockEmptyMessage: 'No hay contratos disponibles.',
  contractLoadFailedMessage: 'No se pudo cargar la informacion de contrato.',
  contractBlockStatusActive: 'Activo',
  contractBlockStatusClosed: 'Cerrado',
  contractBlockPeriodLabel: 'Periodo',
  contractBlockOpenPeriodLabel: 'actual',
  laborClassificationBlockTitle: 'Clasificacion laboral',
  laborClassificationBlockCurrentLabel: 'Clasificacion actual',
  laborClassificationBlockCurrentActiveSectionLabel: 'Clasificacion activa',
  laborClassificationBlockCurrentSectionLabel: 'Clasificacion actual',
  laborClassificationBlockCurrentActiveLabel: 'Clasificacion activa actual.',
  laborClassificationBlockCurrentActiveMostRecentLabel:
    'Hay varias clasificaciones activas; se muestra la mas reciente.',
  laborClassificationBlockCurrentLatestClosedLabel:
    'No hay clasificacion activa; se muestra la ultima clasificacion registrada.',
  laborClassificationBlockHistoryTitle: 'Historial de clasificaciones',
  laborClassificationBlockHistoryEmptyMessage: 'Sin periodos anteriores registrados.',
  laborClassificationBlockEmptyMessage: 'No hay clasificaciones laborales disponibles.',
  laborClassificationLoadFailedMessage: 'No se pudo cargar la informacion de clasificacion laboral.',
  laborClassificationBlockStatusActive: 'Activa',
  laborClassificationBlockStatusClosed: 'Cerrada',
  laborClassificationBlockPeriodLabel: 'Periodo',
  laborClassificationBlockOpenPeriodLabel: 'actual',
  laborClassificationBlockAgreementLabel: 'Convenio',
  laborClassificationBlockCategoryLabel: 'Categoria',
  laborFutureBlockTitle: 'Evolucion laboral',
  laborFutureBlockDescription:
    'Preparado para eventos de movilidad, cambios de categoria y transiciones de jornada.',
  currentEmployeeKeyLabel: 'Employee business key',
  currentEmployeeLabel: 'Employee number',
  placeholderMessage: 'This section is intentionally minimal and ready for OpenAPI integration.',
} as const;
