export const employeeTexts = {
  masterTitle: 'Employees',
  masterSubtitle: 'Search by business key and select an employee to open vertical sections.',
  searchLabel: 'Search employee',
  searchPlaceholder: 'Rule system, type, number, name or work center',
  openAction: 'Open first result',
  resultEmployeesTitle: 'Matching employees',
  noResultEmployeesTitle: 'No matching employees',
  noResultEmployeesDescription: 'Adjust search criteria to find employees by business key.',
  detailPanelTitle: 'Employee detail',
  detailPanelSubtitle: 'Business view of the employee profile, aligned with current vertical routes.',
  emptyDetailTitle: 'Select an employee to start',
  emptyDetailDescription:
    'Use the employee list to open a detail area. No technical IDs are used in this flow.',
  detailIdentityTitle: 'Employee identity',
  detailAvatarPlaceholderAriaLabel: 'Employee avatar placeholder',
  detailHeaderRuleSystemLabel: 'Rule system',
  detailHeaderEmployeeTypeLabel: 'Employee type',
  detailHeaderEmployeeNumberLabel: 'Employee number',
  detailHeaderWorkCenterLabel: 'Work center',
  detailHeaderStatusLabel: 'Status',
  detailHeaderEditAction: 'Editar nombre',
  detailHeaderEditPopoverTitle: 'Editar identidad base',
  detailHeaderFirstNameLabel: 'Nombre',
  detailHeaderLastName1Label: 'Primer apellido',
  detailHeaderLastName2Label: 'Segundo apellido',
  detailHeaderPreferredNameLabel: 'Nombre preferido',
  detailHeaderSaveAction: 'Guardar',
  detailHeaderCancelAction: 'Cancelar',
  detailHeaderUpdateErrorMessage: 'No se pudo actualizar la identidad del empleado. Reintenta.',
  detailHeaderUpdateSuccessMessage: 'Identidad actualizada correctamente.',
  detailHeaderAvatarFallback: 'NA',
  unknownEmployeeName: 'External employee context',
  unknownEmployeeWorkCenter: 'Unknown work center',
  unknownEmployeeStatus: 'Unknown status',
  detailLoadingMessage: 'Cargando detalle del empleado...',
  detailNotFoundMessage: 'No se encontro detalle para la clave de negocio seleccionada.',
  detailLoadFailedMessage: 'No se pudo cargar el detalle del empleado. Reintenta navegando de nuevo.',
  overviewNavLabel: 'Overview',
  contactNavLabel: 'Contact',
  presenceNavLabel: 'Presence',
  detailAreasNavLabel: 'Employee business areas',
  summaryAreaLabel: 'Resumen',
  personalAreaLabel: 'Personales',
  laborAreaLabel: 'Laborales',
  organizationalAreaLabel: 'Organizativos',
  organizationCostCenterAreaLabel: 'Cost center',
  organizationAssignmentAreaLabel: 'Assignment',
  organizationLocationAreaLabel: 'Location',
  organizationDepartmentAreaLabel: 'Department',
  organizationManagerAreaLabel: 'Manager',
  payrollAreaLabel: 'Nomina',
  areaDisabledLabel: 'Disponible en siguiente iteracion',
  navRoutingHint:
    'Personales, Laborales y Organizativos ya navegan sobre verticales activos. Nomina queda preparada.',
  timelineTitle: 'Journey',
  timelineEventsSingularLabel: 'evento',
  timelineEventsPluralLabel: 'eventos',
  timelineLastEventLabel: 'Ultimo',
  timelineExpandActionLabel: 'Expandir journey',
  timelineCollapseActionLabel: 'Contraer journey',
  timelineStatusCompletedLabel: 'Completado',
  timelineStatusCurrentLabel: 'Actual',
  timelineStatusFutureLabel: 'Futuro',
  timelineNoEventsMessage: 'No hay eventos disponibles.',
  timelineLoadingMessage: 'Cargando journey del empleado...',
  timelineLoadFailedMessage: 'No se pudo cargar el journey del empleado.',
  sectionShellCreateAction: 'Crear',
  sectionShellEditAction: 'Editar',
  sectionShellCancelAction: 'Cancelar',
  sectionShellBusyMessage: 'Procesando cambios...',
  sectionDemoTitle: 'Seccion editable (demo)',
  sectionDemoSubtitle: 'Patron base para separar estado local de UI y datos remotos.',
  sectionDemoViewMessage: 'Estado de lectura. Usa Crear o Editar para abrir modo de trabajo local.',
  sectionDemoCreatingMessage: 'Modo creating. Simula la captura de un nuevo registro sin backend real.',
  sectionDemoEditingMessage: 'Modo editing. Simula cambios locales antes de confirmar envio.',
  sectionDemoConfirmingMessage: 'Modo confirming. Punto intermedio antes de ejecutar una accion destructiva.',
  sectionDemoSubmitCreateAction: 'Simular submitCreate()',
  sectionDemoSubmitEditAction: 'Simular submitEdit()',
  sectionDemoConfirmCloseAction: 'Simular confirmClose()',
  sectionDemoCreateSuccessMessage: 'Demo: alta simulada completada.',
  sectionDemoEditSuccessMessage: 'Demo: edicion simulada completada.',
  sectionDemoDeleteSuccessMessage: 'Demo: baja simulada completada.',
  sectionDemoCloseSuccessMessage: 'Demo: cierre simulado completado.',
  slotDemoTitle: 'Contactos por slot (demo)',
  slotDemoSubtitle: 'Patron reusable para alta, edicion y baja por fila con una sola operacion activa.',
  slotManageAction: 'Gestionar',
  slotExitManageAction: 'Salir de gestion',
  slotAddAction: 'Agregar',
  slotEditAction: 'Editar',
  slotDeleteAction: 'Eliminar',
  slotCancelAction: 'Cancelar',
  slotSaveCreateAction: 'Guardar alta',
  slotSaveEditAction: 'Guardar cambios',
  slotConfirmDeleteMessage: 'Confirma la baja de este registro.',
  slotConfirmDeleteAction: 'Confirmar baja',
  slotEmptyMessage: 'No hay registros cargados.',
  slotKeyFieldLabel: 'Tipo',
  slotValueFieldLabel: 'Valor',
  slotDuplicateKeyErrorMessage: 'No se puede repetir un tipo ya existente.',
  slotCreateSuccessMessage: 'Demo slot: alta simulada completada.',
  slotEditSuccessMessage: 'Demo slot: edicion simulada completada.',
  slotDeleteSuccessMessage: 'Demo slot: baja simulada completada.',
  overviewPanelTitle: 'Employee overview',
  overviewPanelSubtitle: 'Initial summary zone for the employee vertical.',
  contactPanelTitle: 'Employee contact',
  contactPanelSubtitle: 'Base area for contact maintenance and history.',
  presencePanelTitle: 'Employee presence',
  presencePanelSubtitle: 'Base area for presence assignments and timeline.',
  summaryAreaTitle: 'Resumen general',
  summaryAreaSubtitle: 'Contexto administrativo rapido de la ficha.',
  summaryProfileBlockTitle: 'Identidad funcional',
  summaryProfileBlockDescription:
    'Clave de negocio activa y estado de lectura actual para iniciar navegacion segura.',
  summaryLifecycleBlockTitle: 'Hitos laborales',
  summaryLifecycleBlockDescription:
    'Esta zona consolidara altas, cambios y cierres en cuanto exista timeline agregado de backend.',
  summaryPendingBlockTitle: 'Proximos pasos',
  summaryPendingBlockDescription:
    'Preparado para alertas operativas: datos incompletos, revisiones y validaciones pendientes.',
  personalAreaTitle: 'Personales',
  personalAreaSubtitle: 'Bloques de informacion personal y de contacto.',
  personalContactsBlockTitle: 'Contactos',
  personalContactsBlockDescription:
    'Espacio para telefono, email y medios principales de contacto del empleado.',
  contactBlockTitle: 'Contactos',
  contactBlockSubtitle: 'Medios principales de contacto del empleado.',
  contactBlockPrimaryPhoneLabel: 'Telefono principal',
  contactBlockPrimaryEmailLabel: 'Email principal',
  contactBlockSecondaryTitle: 'Otros contactos',
  contactBlockCopyAction: 'Copiar',
  contactBlockEmptyMessage: 'No hay informacion de contacto disponible.',
  contactBlockTypePhone: 'Telefono',
  contactBlockTypeEmail: 'Email',
  contactBlockTypeOther: 'Otro',
  contactsSectionTitle: 'Contactos',
  contactsSectionManageAction: 'Gestionar',
  contactsSectionExitManageAction: 'Salir',
  contactsSectionAddAction: 'Agregar contacto',
  contactsSectionEditAction: 'Editar',
  contactsSectionDeleteAction: 'Eliminar',
  contactsSectionCancelAction: 'Cancelar',
  contactsSectionSaveCreateAction: 'Guardar',
  contactsSectionSaveEditAction: 'Guardar',
  contactsSectionConfirmDeleteMessage: 'Confirma la eliminacion de este contacto.',
  contactsSectionConfirmDeleteAction: 'Confirmar eliminacion',
  contactsSectionEmptyMessage: 'No hay contactos cargados.',
  contactsSectionKeyFieldLabel: 'Tipo de contacto',
  contactsSectionValueFieldLabel: 'Valor de contacto',
  contactsSectionRequestFailedMessage: 'No se pudo procesar la operacion de contactos. Reintenta.',
  contactsSectionDuplicateTypeMessage: 'Ya existe un contacto para ese tipo.',
  contactsSectionCreateSuccessMessage: 'Contacto creado correctamente.',
  contactsSectionEditSuccessMessage: 'Contacto actualizado correctamente.',
  contactsSectionDeleteSuccessMessage: 'Contacto eliminado correctamente.',
  identifiersSectionTitle: 'Identificadores',
  identifiersSectionManageAction: 'Gestionar',
  identifiersSectionExitManageAction: 'Salir',
  identifiersSectionAddAction: 'Agregar identificador',
  identifiersSectionEditAction: 'Editar',
  identifiersSectionDeleteAction: 'Eliminar',
  identifiersSectionCancelAction: 'Cancelar',
  identifiersSectionSaveCreateAction: 'Guardar',
  identifiersSectionSaveEditAction: 'Guardar',
  identifiersSectionConfirmDeleteMessage: 'Confirma la eliminacion de este identificador.',
  identifiersSectionConfirmDeleteAction: 'Confirmar eliminacion',
  identifiersSectionEmptyMessage: 'No hay identificadores cargados.',
  identifiersSectionKeyFieldLabel: 'Tipo de identificador',
  identifiersSectionValueFieldLabel: 'Valor del identificador',
  identifiersSectionIssuingCountryLabel: 'Pais emisor',
  identifiersSectionExpirationDateLabel: 'Fecha de caducidad',
  identifiersSectionIsPrimaryLabel: 'Identificador principal',
  identifiersSectionRequestFailedMessage:
    'No se pudo procesar la operacion de identificadores. Reintenta.',
  identifiersSectionDuplicateTypeMessage: 'Ya existe un identificador para ese tipo.',
  identifiersSectionPrimaryBadge: 'Principal',
  identifiersSectionExpirationPrefix: 'Caduca',
  identifiersSectionCreateSuccessMessage: 'Identificador creado correctamente.',
  identifiersSectionEditSuccessMessage: 'Identificador actualizado correctamente.',
  identifiersSectionDeleteSuccessMessage: 'Identificador eliminado correctamente.',
  identifiersSectionSubtitle:
    'Gestiona los identificadores funcionales del empleado. Algunos incluyen pais emisor, caducidad o marca principal.',
  personalLoadingMessage: 'Cargando datos personales...',
  contactLoadingMessage: 'Cargando informacion de contacto...',
  contactLoadFailedMessage: 'No se pudo cargar la informacion de contacto.',
  contactBlockPlaceholderNote:
    'Informacion mostrada en modo placeholder hasta disponer de lectura OpenAPI para contactos.',
  personalAddressesBlockTitle: 'Direcciones',
  addressBlockPrimaryLabel: 'Direccion principal',
  addressBlockSecondaryTitle: 'Otras direcciones',
  addressBlockEmptyMessage: 'No hay informacion de direcciones disponible.',
  addressLoadingMessage: 'Cargando informacion de direcciones...',
  addressLoadFailedMessage: 'No se pudo cargar la informacion de direcciones.',
  addressesSectionTitle: 'Direcciones',
  addressesSectionManageAction: 'Gestionar',
  addressesSectionExitManageAction: 'Salir',
  addressesSectionAddAction: 'Agregar direccion',
  addressesSectionEditCurrentAction: 'Corregir direccion actual',
  addressesSectionCloseAction: 'Cerrar',
  addressesSectionCancelAction: 'Cancelar',
  addressesSectionSaveCreateAction: 'Guardar',
  addressesSectionSaveEditCurrentAction: 'Guardar correccion',
  addressesSectionConfirmCloseMessage: 'Confirma el cierre de esta direccion.',
  addressesSectionConfirmCloseAction: 'Confirmar cierre',
  addressesSectionEmptyMessage: 'No hay direcciones cargadas.',
  addressesSectionRequestFailedMessage: 'No se pudo procesar la operacion de direcciones. Reintenta.',
  addressesSectionCreateSuccessMessage: 'Direccion creada correctamente.',
  addressesSectionEditCurrentSuccessMessage: 'Direccion corregida correctamente.',
  addressesSectionCloseSuccessMessage: 'Direccion cerrada correctamente.',
  addressesSectionEditCurrentHint: 'Corrigiendo la direccion vigente del empleado.',
  addressesSectionSubtitle:
    'Mantiene la direccion vigente y el historico de residencias. Puedes corregir la actual, agregar una nueva o cerrar la vigente.',
  addressesSectionCurrentStatus: 'Actual',
  addressesSectionClosedStatus: 'Cerrada',
  addressesSectionCurrentPeriodLabel: 'actual',
  addressesSectionTypeLabel: 'Tipo de direccion',
  addressesSectionStreetLabel: 'Calle',
  addressesSectionCityLabel: 'Ciudad',
  addressesSectionCountryLabel: 'Pais',
  addressesSectionPostalCodeLabel: 'Codigo postal',
  addressesSectionRegionLabel: 'Region',
  addressesSectionStartDateLabel: 'Fecha inicio',
  workCenterSectionTitle: 'Centro de trabajo',
  workCenterSectionSubtitle:
    'Gestiona la asignacion vigente y el historico de centros de trabajo. Permite alta, cierre y correccion administrativa de ocurrencias.',
  workCenterSectionManageAction: 'Administrar asignaciones',
  workCenterSectionExitManageAction: 'Salir',
  workCenterSectionAddAction: 'Agregar asignacion',
  workCenterSectionCorrectAction: 'Corregir ocurrencia',
  workCenterSectionCloseAction: 'Cerrar',
  workCenterSectionDeleteAction: 'Eliminar',
  workCenterSectionCancelAction: 'Cancelar',
  workCenterSectionSaveCreateAction: 'Guardar',
  workCenterSectionSaveCorrectAction: 'Guardar correccion',
  workCenterSectionConfirmCloseMessage: 'Confirma el cierre de esta asignacion.',
  workCenterSectionConfirmCloseAction: 'Confirmar cierre',
  workCenterSectionConfirmDeleteMessage:
    'Vas a eliminar esta asignacion de centro de trabajo. Esta accion no se puede deshacer.',
  workCenterSectionConfirmDeleteAction: 'Confirmar eliminacion',
  workCenterSectionEmptyMessage: 'No hay asignaciones de centro de trabajo cargadas.',
  workCenterSectionRequestFailedMessage:
    'No se pudo procesar la operacion de centro de trabajo. Reintenta.',
  workCenterSectionOverlapMessage:
    'La asignacion se solapa con otra ocurrencia vigente o historica para este empleado.',
  workCenterSectionOutsidePresenceMessage:
    'El periodo de centro de trabajo debe estar dentro de un periodo de presencia del empleado.',
  workCenterSectionCatalogNotFoundMessage:
    'El centro de trabajo indicado no existe en el catalogo disponible.',
  workCenterSectionNotFoundMessage:
    'No se encontro la asignacion seleccionada de centro de trabajo.',
  workCenterSectionAlreadyClosedMessage:
    'La asignacion ya esta cerrada y no admite un nuevo cierre.',
  workCenterSectionFunctionalInvalidPeriodMessage:
    'El periodo informado no es valido para esta operacion de centro de trabajo.',
  workCenterSectionDeleteForbiddenAtPresenceStartMessage:
    'No se puede eliminar esta asignacion porque inicia una presence del empleado. Corrigela si necesitas cambiarla.',
  workCenterSectionDeleteDisabledPresenceStartReason:
    'No eliminable: inicia una presence del empleado. Usa Corregir ocurrencia.',
  workCenterSectionLoadFailedMessage:
    'No se pudo cargar la informacion de centro de trabajo.',
  workCenterSectionCreateSuccessMessage: 'Asignacion creada correctamente.',
  workCenterSectionCorrectSuccessMessage: 'Asignacion corregida correctamente.',
  workCenterSectionCloseSuccessMessage: 'Asignacion cerrada correctamente.',
  workCenterSectionDeleteSuccessMessage: 'Asignacion eliminada correctamente.',
  workCenterSectionInvalidPeriodMessage:
    'El periodo es invalido. La fecha fin no puede ser anterior a la fecha inicio.',
  workCenterSectionCloseDateInvalidMessage:
    'La fecha de cierre debe ser igual o posterior a la fecha de inicio de la asignacion.',
  workCenterSectionCurrentStatus: 'Vigente',
  workCenterSectionClosedStatus: 'Historica',
  workCenterSectionCurrentPeriodLabel: 'actual',
  workCenterSectionPeriodPrefix: 'Periodo',
  workCenterSectionAssignmentPrefix: 'Asignacion',
  workCenterSectionAssignmentLabel: 'Numero de asignacion',
  workCenterSectionCorrectionHint: 'Corrigiendo la ocurrencia seleccionada sin crear una nueva asignacion.',
  workCenterSectionCloseHint: 'Define la fecha de cierre para finalizar la vigencia de la asignacion actual.',
  workCenterSectionCodeLabel: 'Centro de trabajo',
  workCenterSectionStartDateLabel: 'Fecha inicio',
  workCenterSectionEndDateLabel: 'Fecha fin',
  workCenterSectionCloseDateLabel: 'Fecha de cierre',
  personalIdentifiersBlockTitle: 'Identificadores',
  identifierBlockPrimaryLabel: 'Identificador principal',
  identifierBlockSecondaryTitle: 'Otros identificadores',
  identifierBlockEmptyMessage: 'No hay identificadores disponibles.',
  identifierLoadFailedMessage: 'No se pudo cargar la informacion de identificadores.',
  identifierBlockIssuingCountryLabel: 'Pais emisor',
  identifierBlockExpirationDateLabel: 'Expira',
  personalAddressesBlockDescription:
    'Bloque preparado para direccion principal, historico y vigencias.',
  laborAreaTitle: 'Laborales',
  laborAreaSubtitle: 'Bloques vinculados a presencia, condicion contractual y clasificacion laboral.',
  laborLoadingMessage: 'Cargando datos laborales...',
  organizationLoadingMessage: 'Cargando datos organizativos...',
  organizationFutureTitle: 'Proximas asignaciones organizativas',
  organizationFutureDescription:
    'Este bloque prepara la incorporacion progresiva de cost center, assignment y otras asignaciones organizativas.',
  laborPresenceBlockTitle: 'Presence',
  laborPresenceBlockDescription:
    'Area conectada al vertical de presencia con capacidad de historial y estado activo.',
  presenceBlockTitle: 'Presencia',
  presenceBlockCurrentLabel: 'Presencia actual',
  presenceBlockCurrentActiveSectionLabel: 'Presencia activa',
  presenceBlockCurrentSectionLabel: 'Presencia actual',
  presenceBlockCurrentActiveLabel: 'Presencia activa actual.',
  presenceBlockCurrentActiveMostRecentLabel:
    'Hay varias presencias activas; se muestra la mas reciente.',
  presenceBlockCurrentLatestClosedLabel:
    'No hay presencia activa; se muestra la ultima presencia registrada.',
  presenceBlockHistoryTitle: 'Historial de presencias',
  presenceBlockHistoryEmptyMessage: 'Sin periodos anteriores registrados.',
  presenceBlockEmptyMessage: 'No hay presencias disponibles.',
  presenceLoadFailedMessage: 'No se pudo cargar la informacion de presencia.',
  presenceBlockStatusActive: 'Activa',
  presenceBlockStatusClosed: 'Cerrada',
  presenceBlockPeriodLabel: 'Periodo',
  presenceBlockPeriodNumberPrefix: 'periodo',
  presenceBlockOpenPeriodLabel: 'actual',
  presenceBlockCompanyLabel: 'Compania',
  presenceBlockEntryReasonLabel: 'Motivo entrada',
  presenceBlockExitReasonLabel: 'Motivo salida',
  laborContractBlockTitle: 'Contract',
  laborContractBlockDescription:
    'Bloque reservado para tipo contractual, fechas clave y cambios vigentes.',
  contractBlockTitle: 'Contrato',
  contractBlockCurrentLabel: 'Contrato actual',
  contractBlockCurrentActiveSectionLabel: 'Contrato activo',
  contractBlockCurrentSectionLabel: 'Contrato actual',
  contractBlockCurrentActiveLabel: 'Contrato activo actual.',
  contractBlockCurrentActiveMostRecentLabel:
    'Hay varios contratos activos; se muestra el mas reciente.',
  contractBlockCurrentLatestClosedLabel:
    'No hay contrato activo; se muestra el ultimo contrato registrado.',
  contractBlockHistoryTitle: 'Historial de contratos',
  contractBlockHistoryEmptyMessage: 'Sin periodos contractuales anteriores registrados.',
  contractBlockEmptyMessage: 'No hay contratos disponibles.',
  contractLoadFailedMessage: 'No se pudo cargar la informacion de contrato.',
  contractBlockStatusActive: 'Activo',
  contractBlockStatusClosed: 'Cerrado',
  contractBlockPeriodLabel: 'Periodo',
  contractBlockOpenPeriodLabel: 'actual',
  laborClassificationBlockTitle: 'Clasificacion laboral',
  laborClassificationBlockCurrentLabel: 'Clasificacion actual',
  laborClassificationBlockCurrentActiveSectionLabel: 'Clasificacion activa',
  laborClassificationBlockCurrentSectionLabel: 'Clasificacion actual',
  laborClassificationBlockCurrentActiveLabel: 'Clasificacion activa actual.',
  laborClassificationBlockCurrentActiveMostRecentLabel:
    'Hay varias clasificaciones activas; se muestra la mas reciente.',
  laborClassificationBlockCurrentLatestClosedLabel:
    'No hay clasificacion activa; se muestra la ultima clasificacion registrada.',
  laborClassificationBlockHistoryTitle: 'Historial de clasificaciones',
  laborClassificationBlockHistoryEmptyMessage: 'Sin periodos anteriores registrados.',
  laborClassificationBlockEmptyMessage: 'No hay clasificaciones laborales disponibles.',
  laborClassificationLoadFailedMessage: 'No se pudo cargar la informacion de clasificacion laboral.',
  laborClassificationBlockStatusActive: 'Activa',
  laborClassificationBlockStatusClosed: 'Cerrada',
  laborClassificationBlockPeriodLabel: 'Periodo',
  laborClassificationBlockOpenPeriodLabel: 'actual',
  laborClassificationBlockAgreementLabel: 'Convenio',
  laborClassificationBlockCategoryLabel: 'Categoria',
  laborClassificationSectionTitle: 'Clasificacion laboral',
  laborClassificationSectionSubtitle:
    'Gestiona la clasificacion laboral vigente y su historico.',
  laborClassificationSectionManageAction: 'Cambiar clasificacion desde fecha',
  laborClassificationSectionExitManageAction: 'Salir',
  laborClassificationSectionReplaceAction: 'Cambiar clasificacion desde fecha',
  laborClassificationSectionCorrectAction: 'Corregir ocurrencia',
  laborClassificationSectionCloseAction: 'Cerrar',
  laborClassificationSectionDeleteAction: 'Eliminar',
  laborClassificationSectionCancelAction: 'Cancelar',
  laborClassificationSectionSaveReplaceAction: 'Guardar reemplazo',
  laborClassificationSectionSaveCorrectAction: 'Guardar correccion',
  laborClassificationSectionConfirmCloseMessage:
    'Confirma el cierre de esta ocurrencia de clasificacion laboral.',
  laborClassificationSectionConfirmCloseAction: 'Confirmar cierre',
  laborClassificationSectionConfirmDeleteMessage:
    'La eliminacion no esta habilitada para clasificacion laboral.',
  laborClassificationSectionConfirmDeleteAction: 'Confirmar eliminacion',
  laborClassificationSectionEmptyMessage: 'No hay clasificaciones laborales cargadas.',
  laborClassificationSectionStatusActive: 'Vigente',
  laborClassificationSectionStatusClosed: 'Historica',
  laborClassificationSectionCurrentPeriodLabel: 'actual',
  laborClassificationSectionPeriodPrefix: 'Periodo',
  laborClassificationSectionCategoryPrefix: 'Categoria',
  laborClassificationSectionReplaceHint:
    'El reemplazo crea una nueva ocurrencia desde la fecha efectiva y ajusta la vigencia anterior segun reglas del backend.',
  laborClassificationSectionEffectiveDateLabel: 'Fecha efectiva',
  laborClassificationSectionAgreementLabel: 'Convenio',
  laborClassificationSectionSelectAgreementPlaceholder: 'Selecciona un convenio',
  laborClassificationSectionAgreementPlaceholder: 'Codigo de convenio',
  laborClassificationSectionCategoryLabel: 'Categoria',
  laborClassificationSectionSelectCategoryPlaceholder: 'Selecciona una categoria',
  laborClassificationSectionCategoryPlaceholder: 'Codigo de categoria',
  laborClassificationSectionLookupPendingHint:
    'La seleccion asistida de convenio y categoria llegara cuando esten disponibles las maestras.',
  laborClassificationSectionOccurrenceStartDateLabel: 'Inicio',
  laborClassificationSectionCorrectHint:
    'La correccion actualiza la ocurrencia seleccionada manteniendo su fecha de inicio original.',
  laborClassificationSectionCloseHint:
    'Indica la fecha de cierre para finalizar la ocurrencia vigente sin eliminar historial.',
  laborClassificationSectionCloseDateLabel: 'Fecha de cierre',
  laborClassificationSectionInvalidDataMessage:
    'Completa los datos obligatorios para continuar con la operacion.',
  laborClassificationSectionCloseDateInvalidMessage:
    'La fecha de cierre debe ser igual o posterior al inicio de la ocurrencia.',
  laborClassificationSectionOverlapMessage:
    'La clasificacion se solapa con otra ocurrencia vigente o historica del empleado.',
  laborClassificationSectionOutsidePresenceMessage:
    'La clasificacion debe quedar dentro de un periodo de presencia del empleado.',
  laborClassificationSectionIncompleteCoverageMessage:
    'La operacion deja un hueco temporal no permitido en la cobertura de clasificacion laboral.',
  laborClassificationSectionInvalidPeriodMessage:
    'El periodo informado no es valido para esta operacion de clasificacion laboral.',
  laborClassificationSectionAlreadyClosedMessage:
    'La ocurrencia ya esta cerrada y no admite un nuevo cierre.',
  laborClassificationSectionNotFoundMessage:
    'No se encontro la ocurrencia seleccionada de clasificacion laboral.',
  laborClassificationSectionAgreementNotFoundMessage:
    'El convenio indicado no existe para el sistema de reglas activo.',
  laborClassificationSectionAgreementCategoryNotFoundMessage:
    'La categoria indicada no existe para el sistema de reglas activo.',
  laborClassificationSectionAgreementCategoryRelationInvalidMessage:
    'La categoria no pertenece al convenio seleccionado para esta fecha efectiva.',
  laborClassificationSectionRequestFailedMessage:
    'No se pudo procesar la operacion de clasificacion laboral. Reintenta.',
  laborClassificationSectionCatalogRequestFailedMessage:
    'No se pudo cargar el catalogo de convenios y categorias. Reintenta.',
  laborClassificationSectionReplaceSuccessMessage: 'Clasificacion reemplazada correctamente.',
  laborClassificationSectionCorrectSuccessMessage: 'Clasificacion corregida correctamente.',
  laborClassificationSectionCloseSuccessMessage: 'Clasificacion cerrada correctamente.',
  laborFutureBlockTitle: 'Evolucion laboral',
  laborFutureBlockDescription:
    'Preparado para eventos de movilidad, cambios de categoria y transiciones de jornada.',
  currentEmployeeKeyLabel: 'Employee business key',
  currentEmployeeLabel: 'Employee number',
  placeholderMessage: 'This section is intentionally minimal and ready for OpenAPI integration.',
} as const;
